In [1]:
import torch
from torch.nn import L1Loss
inputs = torch.tensor([1,2,3],dtype=torch.float32)
targets = torch.tensor([1,2,5],dtype=torch.float32)
inputs = torch.reshape(inputs,(1,1,1,3))
targets = torch.reshape(targets,(1,1,1,3))
loss = L1Loss()  # 默认为 maen
result = loss(inputs,targets)
print(result)

tensor(0.6667)


In [5]:
import torch
from torch.nn import L1Loss
inputs = torch.tensor([1,2,3],dtype=torch.float32)
targets = torch.tensor([1,2,5],dtype=torch.float32)
inputs = torch.reshape(inputs,(1,1,1,3))
targets = torch.reshape(targets,(1,1,1,3))
loss = L1Loss(reduction='sum') # 修改为sum，三个值的差值，然后取和
result = loss(inputs,targets)
print(result)

tensor(2.)


In [4]:
import torch
from torch.nn import L1Loss
from torch import nn
inputs = torch.tensor([1,2,3],dtype=torch.float32)
targets = torch.tensor([1,2,5],dtype=torch.float32)
inputs = torch.reshape(inputs,(1,1,1,3))
targets = torch.reshape(targets,(1,1,1,3))
loss_mse = nn.MSELoss()
result_mse = loss_mse(inputs,targets)
print(result_mse)

tensor(1.3333)


In [3]:
import torch
from torch.nn import L1Loss
from torch import nn

x = torch.tensor([0.1,0.2,0.3])
y = torch.tensor([1])
x = torch.reshape(x,(1,3)) # 1的 batch_size，有三类
loss_cross = nn.CrossEntropyLoss()
result_cross = loss_cross(x,y)
print(result_cross)

tensor(1.1019)


In [2]:
import torch
import torchvision
from torch import nn 
from torch.nn import Conv2d, MaxPool2d, Flatten, Linear, Sequential
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter

dataset = torchvision.datasets.CIFAR10("./dataset",train=False,transform=torchvision.transforms.ToTensor(),download=True)       
dataloader = DataLoader(dataset, batch_size=1,drop_last=True)

class Tudui(nn.Module):
    def __init__(self):
        super(Tudui, self).__init__()        
        self.model1 = Sequential(
            Conv2d(3,32,5,padding=2),
            MaxPool2d(2),
            Conv2d(32,32,5,padding=2),
            MaxPool2d(2),
            Conv2d(32,64,5,padding=2),
            MaxPool2d(2),
            Flatten(),
            Linear(1024,64),
            Linear(64,10)
        )
        
    def forward(self, x):
        x = self.model1(x)
        return x
    
tudui = Tudui()
for data in dataloader:
    imgs, targets = data
    outputs = tudui(imgs)
    print(outputs)
    print(targets)

Files already downloaded and verified
tensor([[-0.0103, -0.0925,  0.1166, -0.1375,  0.1294,  0.0318, -0.0060, -0.0404,
         -0.0490, -0.0760]], grad_fn=<AddmmBackward0>)
tensor([3])
tensor([[-0.0012, -0.0949,  0.1003, -0.1597,  0.1145,  0.0308, -0.0067, -0.0376,
         -0.0817, -0.0617]], grad_fn=<AddmmBackward0>)
tensor([8])
tensor([[ 0.0048, -0.1085,  0.1027, -0.1468,  0.1210,  0.0284, -0.0144, -0.0361,
         -0.0546, -0.0814]], grad_fn=<AddmmBackward0>)
tensor([8])
tensor([[-0.0028, -0.1020,  0.1010, -0.1618,  0.1194,  0.0396, -0.0114, -0.0393,
         -0.0693, -0.0785]], grad_fn=<AddmmBackward0>)
tensor([0])
tensor([[-0.0071, -0.0990,  0.1071, -0.1400,  0.1123,  0.0248, -0.0064, -0.0515,
         -0.0523, -0.0707]], grad_fn=<AddmmBackward0>)
tensor([6])
tensor([[-0.0042, -0.1006,  0.1078, -0.1257,  0.1239,  0.0345, -0.0054, -0.0543,
         -0.0444, -0.0712]], grad_fn=<AddmmBackward0>)
tensor([6])
tensor([[-0.0071, -0.1131,  0.1143, -0.1220,  0.1195,  0.0225, -0.0059, -0